'use client';

import { Navbar } from '@/components/layout/navbar';
import { getConfig, queryClient } from '@/lib/wallet/config';
import { QueryClientProvider } from '@tanstack/react-query';
import { Geist, Geist_Mono, Nunito_Sans } from 'next/font/google';
import { Toaster } from 'sonner';
import { WagmiProvider } from 'wagmi';
import './globals.css';

const nunitoSans = Nunito_Sans({ variable: '--font-sans' });

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <WagmiProvider config={getConfig()}>
      <QueryClientProvider client={queryClient}>
        <html lang="en" className={nunitoSans.variable}>
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Navbar />

            <main className="pb-20">{children}</main>
            <Toaster />
          </body>
        </html>
      </QueryClientProvider>
    </WagmiProvider>
  );
}
