services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "squid"]
      interval: 5s
      timeout: 5s
      retries: 5
    # Uncomment for logging all SQL statements
    # command: ["postgres", "-c", "log_statement=all"]
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: polkabill-squid
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - GQL_PORT=4350
      - RPC_BASE_SEPOLIA_HTTP=${RPC_BASE_SEPOLIA_HTTP}
    ports:
      # GraphQL endpoint at port 4350
      - "4350:4350"
    command: ["sqd", "serve:prod"]
    depends_on:
      db:
        condition: service_healthy
  processor:
    image: polkabill-squid
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - RPC_BASE_SEPOLIA_HTTP=${RPC_BASE_SEPOLIA_HTTP}
    ports:
      # prometheus metrics exposed at port 3000
      - "3000:3000"
    command: ["sqd", "process:prod"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: